### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 2,
  "accountNumber": "1439549188",
  "amount": 100000000000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "4420432201",
  "amount": 123
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "763bcd9f7788499383ce0ed3960689bf",
  "accountNumber": "4420432201",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/2b5c5822b1324a97bbc5f8d7af942263
