### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "0421769299",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "0421769299",
  "amount": 123
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "91bfe07df7224c3999df7f2fccb46bd4",
  "accountNumber": "0421769299",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/7f6e805c3ab54479bf33fd8fbd06491b
