### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "3027390411",
  "amount": 100000
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "3027390411",
  "amount": 123
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "8b8d92ae5cef4246980fb0fc8c0910bc",
  "accountNumber": "3027390411",
  "amount": 10
}

### query transaction
GET http://localhost:8080/transaction/7f6e805c3ab54479bf33fd8fbd06491b
